import { geoSpecies } from '@prisma/client';
import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';

export class GeospeciesEnt implements geoSpecies {
  @ApiHideProperty()
  take?: number;

  @ApiHideProperty()
  cursor?: number;
  
  @ApiProperty({
    type: Number,
    required: false,
    description: 'Autoincrement id generated by the database.',
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  PrimaryKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  DBKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  ProjectKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Species: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  AH_SpeciesCover: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  AH_SpeciesCover_n: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  Hgt_Species_Avg: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  Hgt_Species_Avg_n: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Duration: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  GrowthHabit: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  GrowthHabitSub: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  SpeciesKey: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: '',
  })
  DateLoadedInDb: Date;

  @ApiProperty()
  DateVisited: Date;
}
