version: "3.3"
services:
  nest:
  
    # image: landscapedatacommons/nest_api:1.0.0
    image: nestapi
    build:
      context: .
      dockerfile: ./nest/node.Dockerfile
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./nest/.env
    # deploy:
    #   mode: replicated
    #   replicas: 3
    labels:
      - traefik.enable=true # enable traefik
      - traefik.docker.network=proxy # put it in the same network as traefik
      - traefik.http.routers.nest.entrypoints=web # entrypoint chosen on traefik
      - traefik.http.routers.nest.rule=Host(`n.localhost`) # choose any domain
      - traefik.http.routers.nest.service=nest # give the proxied service a name
      - traefik.http.services.nest.loadbalancer.server.port=3000 # loadbalance on this internal port

networks:
  proxy:
    external: true
