version: "3.3"
services:
  nest:
    image: landscapedatacommons/nest_api:1.0.13
    build:
      context: .
      dockerfile: ./nest/node.Dockerfile
    ports:
      - "5016:3000"
    env_file:
      - ./nest/.env
