import { dataLPI } from '@prisma/client';
import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';

export class DatalpiEnt implements dataLPI {
  @ApiHideProperty()
  take?: number;

  @ApiHideProperty()
  cursor?: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Autoincrement id generated by the database.',
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  PrimaryKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  DBKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  ProjectKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  LineKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  RecKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  layer: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  code: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  chckbox: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  ShrubShape: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  FormType: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: '',
  })
  FormDate: Date;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Direction: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  Measure: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  LineLengthAmount: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  SpacingIntervalAmount: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  SpacingType: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  ShowCheckbox: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  CheckboxLabel: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  PointLoc: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  PointNbr: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  source: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: '',
  })
  DateLoadedInDb: Date;

  @ApiProperty()
  DateVisited: Date;
}
