import { tblSchema } from '@prisma/client';
import { ApiProperty } from '@nestjs/swagger';

export class TblSchemaEnt implements tblSchema {
  @ApiProperty({
    type: Number,
    required: false,
    description: 'Autoincrement id generated by the database.',
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Name of table.',
  })
  Table: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Name of field.',
  })
  Field: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Alias of field.',
  })
  Alias: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Description of field.',
  })
  Description: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Postgresql data type of field.',
  })
  DataType: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Length of character if VarChar.',
  })
  Length: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Data type notes',
  })
  DatatypeNotes: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Version of schema used',
  })
  Version: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: 'Date a particular schema was uploaded',
  })
  Uploaded: Date;
}
