import { dataGap } from '@prisma/client';
import { ApiProperty } from '@nestjs/swagger';

export class DatagapEnt implements dataGap {

  @ApiProperty({
    type: Number,
    required: false, 
    description: 'Autoincrement id generated by the database.'
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false, 
    description: 'Unique identifier for each plot-visit.'
  })
  PrimaryKey: string;

  @ApiProperty({
    type: String,
    required: false, 
    description: 'Code denoting original database information about the project.',
  })
  DBKey: string;

  @ApiProperty({
    type: String,
    required: false, 
    description: 'Unique identifier of the broader project under which data were collected.',
    enum: ['NDOW', 'NWERN', 'RHEM', 'BLM-AIM']
  })
  ProjectKey: string;

  @ApiProperty({
    type: String,
    required: false, 
    description: 'Type of gap data: P = perennial canopy gap, B = basal gap, C = canopy gap.',
    enum: ['P', 'B', 'C']
  })
  RecType: string;

  @ApiProperty({
    type: Number,
    required: false
  })
  SeqNo: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  GapStart: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  GapEnd: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  Gap: number;

  @ApiProperty()
  LineKey: string;

  @ApiProperty()
  RecKey: string;

  @ApiProperty()
  FormDate: Date;

  @ApiProperty()
  DateModified: Date;

  @ApiProperty()
  FormType: string;

  @ApiProperty()
  Direction: string;

  @ApiProperty({
    type: Number,
    required: false
  })
  Measure: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  LineLengthAmount: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  GapMin: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  GapData: number;

  @ApiProperty()
  PerennialsCanopy: string;

  @ApiProperty()
  AnnualGrassesCanopy: string;

  @ApiProperty()
  AnnualForbsCanopy: string;

  @ApiProperty()
  OtherCanopy: string;

  @ApiProperty()
  Notes: string;

  @ApiProperty({
    type: Number,
    required: false
  })
  NoCanopyGaps: number;

  @ApiProperty({
    type: Number,
    required: false
  })
  NoBasalGaps: number;

  @ApiProperty()
  DateLoadedInDb: Date;

  @ApiProperty()
  PerennialsBasal: string;

  @ApiProperty()
  AnnualGrassesBasal: string;

  @ApiProperty()
  AnnualForbsBasal: string;

  @ApiProperty()
  OtherBasal: string;

  @ApiProperty()
  source: string;
}
