import { dataDustDeposition } from '@prisma/client';
import { ApiProperty } from '@nestjs/swagger';

export class DatadustdepositionEnt implements dataDustDeposition {
  @ApiProperty({
    type: Number,
    required: false,
    description: 'Autoincrement id generated by the database.',
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Unique key for stack (i.e., MWAC/BSNE mast or DDT).',
  })
  StackID: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Unique identifier of the broader project under which data were collected.',
  })
  ProjectKey: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: 'The date the MWAC/BSNE stack or DDT was established (YYYY-MM-DD).',
  })
  DateEstablished: Date;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Location of DDT or MWAC/BSNE stack.',
  })
  Location: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Notes about the sample collection for the Dust Deposition Trap (DDT) or MWAC/BSNE stack.'
  })
  Notes: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'M = MWAC/BSNE; T = DDT.',
    enum: ['M', 'T'],
  })
  ItemType: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'DDT opening area (cm2).',
  })
  trapOpeningArea: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'GPS coordinate system used.',
  })
  GPSCoordSys: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'GPS datum of plot.',
  })
  Datum: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'GPS zone of plot.',
  })
  Zone: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'UTM easting for position.',
  })
  Easting: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'UTM northing for position.',
  })
  Northing: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'GPS Longitude (convert Easting if entered).',
  })
  Longitude: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'GPS Latitude (convert Northing if entered).',
  })
  Latitude: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Unique key for Dust Deposition data collection.',
  })
  RecKey: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: 'Date that collection occurred.',
  })
  collectDate: Date;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Person who collected the sample.',
  })
  Collector: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Person who performed the lab work.',
  })
  labTech: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Beaker ID.',
  })
  breakerNbr: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Empty beaker weight in grams.',
  })
  emptyWeight: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Weight of Beaker and Oven Dry Sediment in grams (weight cannot be less than empty beaker weight).',
  })
  recordedWeight: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Weight of sediment in grams (recordedWeight - emptyWeight).',
  })
  sedimentWeight: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Entered if data are imported from Excel. Calculated when data are entered into database.',
  })
  daysExposed: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'sedimentWeight/daysExposed (grams/day).',
  })
  sedimentGprDay: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Sample is stored for future use (1 = yes; 0 = no).',
    enum: ['0', '1'],
  })
  sedimentArchived: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'SedimentGperDay/trapOpeningArea (grams/cm2/day).',
  })
  sedimentGperDayByInlet: number;

  @ApiProperty({
    type: Number,
    required: false,
    description: 'Sequence of collected samples if more than one collection is made on the same date.',
  })
  SeqNo: number;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Sample is unusable (1 = yes; 0 = no).',
    enum: ['0', '1'],
  })
  SampleCompromised: string;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Unique identifier for each plot-visit.',
  })
  PrimaryKey: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: 'Date that the data were uploaded into Landscape Data Commons (YYYY-MM-DD).',
  })
  DateLoadedInDB: Date;

  @ApiProperty({
    type: String,
    required: false,
    description: 'Code denoting original database information about the project.',
  })
  DBKey: string;
}
