api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
  traefik:
    address: :8080
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
log:
  level: DEBUG
  # websecure:
  #   address: :443
  #   http:
  #     middlewares:
  #       - secureHeaders@file
  #     tls:
  #       certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  # file:
  #   filename: /configurations/dynamic.yml

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: bonefont.work@gmail.com
#       storage: acme.json
#       keyType: EC384
#       httpChallenge:
#         entryPoint: web