api:
  dashboard: true
  # insecure: true

entryPoints:
  web:
    address: :80

  web-secure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

log:
  level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: bonefont.work@gmail.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web