import { dataSoilStability } from '@prisma/client';
import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';

export class DatasoilstabilityEnt implements dataSoilStability {
  @ApiHideProperty()
  take?: number;

  @ApiHideProperty()
  cursor?: number;
  
  @ApiProperty({
    type: Number,
    required: false,
    description: 'Autoincrement id generated by the database.',
  })
  rid: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  PrimaryKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  DBKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  ProjectKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  RecKey: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  FormType: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: '',
  })
  FormDate: Date;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  LineKey: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  SoilStabSubSurface: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Line: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  Position: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Pos: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Veg: string;

  @ApiProperty({
    type: Number,
    required: false,
    description: '',
  })
  Rating: number;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Hydro: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  Notes: string;

  @ApiProperty({
    type: String,
    required: false,
    description: '',
  })
  source: string;

  @ApiProperty({
    type: Date,
    required: false,
    // example: '2021-08-04',
    description: '',
  })
  DateLoadedInDb: Date;
}
